version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: tcc_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: tccbackend
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tcc_network

volumes:
  mysql_data:

networks:
  tcc_network:
    driver: bridge